// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZlnRJkyxlnq_PnLWyqV8vpX2QvSO1HK8',
    appId: '1:665102315540:web:41353acd086123597eb701',
    messagingSenderId: '665102315540',
    projectId: 'dormlanders-fd518',
    authDomain: 'dormlanders-fd518.firebaseapp.com',
    storageBucket: 'dormlanders-fd518.appspot.com',
    measurementId: 'G-B0GZ5T9GNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsLXXsuSZSPst6BEyCga-9Pi71YQ43EE4',
    appId: '1:665102315540:android:9e9973d6966c62b17eb701',
    messagingSenderId: '665102315540',
    projectId: 'dormlanders-fd518',
    storageBucket: 'dormlanders-fd518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA450UCg30XGO0dZ8mofHjp_8jBqhwSzCU',
    appId: '1:665102315540:ios:c8fc15771f6793267eb701',
    messagingSenderId: '665102315540',
    projectId: 'dormlanders-fd518',
    storageBucket: 'dormlanders-fd518.appspot.com',
    iosBundleId: 'com.example.dormlanders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA450UCg30XGO0dZ8mofHjp_8jBqhwSzCU',
    appId: '1:665102315540:ios:c8fc15771f6793267eb701',
    messagingSenderId: '665102315540',
    projectId: 'dormlanders-fd518',
    storageBucket: 'dormlanders-fd518.appspot.com',
    iosBundleId: 'com.example.dormlanders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZlnRJkyxlnq_PnLWyqV8vpX2QvSO1HK8',
    appId: '1:665102315540:web:fe374801952df6277eb701',
    messagingSenderId: '665102315540',
    projectId: 'dormlanders-fd518',
    authDomain: 'dormlanders-fd518.firebaseapp.com',
    storageBucket: 'dormlanders-fd518.appspot.com',
    measurementId: 'G-R4XQ675YMJ',
  );

}